version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 8081:8081
      - 5050:5050
    env_file:
      - .env
